services:
  backend:
    container_name: mini_editor_backend
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - backend_data:/app/data
    environment:
      DATABASE_URL: "/app/data/db.sqlite" 
      NODE_ENV: development

  frontend:
    container_name: mini_editor_frontend
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://backend:4000
      NODE_ENV: development

volumes:
  backend_data: